apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: latency-test-1
  name: latency-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: latency-test-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: latency-test-1
    spec:
      containers:
      - image: latency-test
        imagePullPolicy: IfNotPresent
        name: latency-test-1
        ports:
        - containerPort: 8080
        env:
          - name: SV_ADDR
            value: "0.0.0.0"
          - name: SV_PORT
            value: "8080"
          - name: SV_DOMAIN
            value: "*"
          - name: SV_PRODUCTION
            value: "false"